- name: Backup WebSphere profiles with -nostop 
  hosts: "{{ variable_host }}"
  #vars_files:
  #  - roles/common/vars/iim.yml
  #  - roles/common/vars/was.yml
  #become: false
  tasks:

    - name: Backup Dmgr profile
      backupProfileConfig:  wasdir=/opt/IBM/WebSphere/BPM/v8.0/ profilename=Dmgr backupdir=/opt/IBM/WebSphere/backup 
      #username=admin password=admin
      become: true
      become_user: wasuser
      #no_log: true
      register: backupProfile
    - debug: var=backupProfile


    - name: Backup ManagedAppServers profile
      backupProfileConfig:  wasdir=/opt/IBM/WebSphere/BPM/v8.0/ profilename=ManagedAppServers backupdir=/opt/IBM/WebSphere/backup 
      #username=admin password=admin
      become: true
      become_user: wasuser
      #no_log: true
      register: backupProfile
    - debug: var=backupProfile
