- name: creates DMGR profile on WASND 8.5
  hosts: "{{ variable_host }}"
  vars_files:
    - roles/common/vars/iim.yml
    - roles/common/vars/was.yml
  become: false
  tasks:


    - name: backup WAS Dmgr
      backupWAS:  state=present wasdir=/opt/IBM/WebSphere/AppServer/ profilename=dmgr username=admin password=admin backupdir=/tmp
      #profile_dmgr: state=present wasdir=/opt/IBM/WebSphere/AppServer/ name=dmgr cell_name=devCell host_name=localhost node_name=devcell-dmgr username=admin password=admin
      register: backupDmgr 
    - debug: var=backupDmgr

