- name: stops JVMs in WebSphere 8.5
  hosts: "{{ variable_host }}"
  tasks:



    - name: Upgrade MessagingCluster 
      bpmProfileUpgrade:  wasdir=/opt/IBM/WebSphere/BPM/v8.0/ profilename=Dmgr state=node targetcluster=MessagingCluster
      become: true
      become_user: wasuser
      register: bpmProfileUpgrade
    - debug: var=bpmProfileUpgrade




