- name: BPM Profile upgrade 
  hosts: "{{ variable_host }}"
  tasks:


    - name: Upgrade AppCluster 
      bpmProfileUpgrade:  wasdir=/opt/IBM/WebSphere/BPM/v8.0/ profilename=Dmgr state=node targetcluster=AppTargetCluster
      become: true
      become_user: wasuser
      register: bpmProfileUpgrade
    - debug: var=bpmProfileUpgrade

    - name: Upgrade SupportCluster
      bpmProfileUpgrade:  wasdir=/opt/IBM/WebSphere/BPM/v8.0/ profilename=Dmgr state=node targetcluster=AppTargetCluster
      become: true
      become_user: wasuser
      register: bpmProfileUpgrade
    - debug: var=bpmProfileUpgrade

    - name: Upgrade MessagingCluster 
      bpmProfileUpgrade:  wasdir=/opt/IBM/WebSphere/BPM/v8.0/ profilename=Dmgr state=node targetcluster=MessagingCluster
      become: true
      become_user: wasuser
      register: bpmProfileUpgrade
    - debug: var=bpmProfileUpgrade




