- name: Start all WebSphere JVM's  
  hosts: "{{ variable_host }}" 
  #vars_files:
  #  - roles/common/vars/iim.yml
  #  - roles/common/vars/was.yml
  #become: false
  tasks:


    - name: start Dmgr
      startDmgr:  wasdir=/opt/IBM/WebSphere/BPM/v8.0/ profilename=Dmgr
      #username=admin password=admin
      become: true
      become_user: wasuser
      #no_log: true
      register: startDmgr
    - debug: var=startDmgr


    - name: start JVM's
      startJVM:  wasdir=/opt/IBM/WebSphere/BPM/v8.0/ profilename=ManagedAppServers
      #username=admin password=admin
      become: true
      become_user: wasuser
      #no_log: true
      register: startJVM
    - debug: var=startJVM



