- name: starts JVMs in WebSphere 8.5
  hosts: "{{ variable_host }}"
#  vars_files:
#    - roles/common/vars/iim.yml
#    - roles/common/vars/was.yml
  #become: false
  tasks:

    - name: start Dmgr 
      startAnyJVM:  wasdir=/opt/IBM/WebSphere/BPM/v8.0/ profilename=Dmgr jvmname=dmgr
      #username=admin password=admin
      become: true
      become_user: wasuser
      #no_log: true
      register: startDmgr
    - debug: var=startDmgr

    - name: start Nodeagent
      startAnyJVM:  wasdir=/opt/IBM/WebSphere/BPM/v8.0/ profilename=ManagedAppServers jvmname=nodeagent
      #username=admin password=admin
      become: true
      become_user: wasuser
      #no_log: true
      register: startDmgr
    - debug: var=startDmgr
